name: Build and Push to Github
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: 'Build and Push to Github'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to Github
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY }}/crbot:latest
          file: Dockerfile
